<?php

namespace Database\Seeders;

use App\Models\MartialArtsClass;
use Illuminate\Database\Seeder;

class ScheduleSessionSeeder extends Seeder
{
    public function run(): void
    {
        $classes = [
            // KIDS
            [
                'name' => 'Little Champions | Intro to Grappling Martial Arts',
                'description' => "Monday 5:00 PM – 6:00 PM\nWednesday 5:00 PM – 6:00 PM (Striking Fundamentals)",
                'category' => 'Kids',
                'type' => 'Grappling',
                'level' => 'Beginner',
                'age_group' => '5-6',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],

            // YOUTH
            [
                'name' => 'Youth Grappling | Novice + Intermediate',
                'description' => "Monday 6:00 PM – 7:00 PM",
                'category' => 'Youth',
                'type' => 'Grappling',
                'level' => 'All Levels',
                'age_group' => '7-9',
                'format' => 'Grappling',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Youth Muay Thai | All Levels',
                'description' => "Wednesday 6:00 PM – 7:00 PM",
                'category' => 'Youth',
                'type' => 'Muay Thai',
                'level' => 'All Levels',
                'age_group' => '7-9',
                'format' => 'Striking',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Youth Empowerment & Private Groups',
                'description' => "Thursday 3:00 PM – 4:00 PM",
                'category' => 'Youth',
                'type' => 'Fitness',
                'level' => 'All Levels',
                'age_group' => '7-9',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Youth Competition Fitness | Functional Fighter Training',
                'description' => "Friday 6:00 PM – 7:00 PM",
                'category' => 'Youth',
                'type' => 'Fitness',
                'level' => 'Intermediate',
                'age_group' => '7-9',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],

            // TEENS
            [
                'name' => 'Teens Brazilian Jiu-Jitsu',
                'description' => "Tuesday 5:00 PM – 6:00 PM",
                'category' => 'Teens',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'All Levels',
                'age_group' => '10-15',
                'format' => 'Grappling',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Teens Martial Arts Muay Thai Striking',
                'description' => "Thursday 5:00 PM – 6:00 PM",
                'category' => 'Teens',
                'type' => 'Muay Thai',
                'level' => 'All Levels',
                'age_group' => '10-15',
                'format' => 'Striking',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Competition BJJ | Grey/White Belt & Above',
                'description' => "Friday 5:00 PM – 6:00 PM",
                'category' => 'Competition',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'Intermediate',
                'age_group' => '7-9',
                'format' => 'Grappling',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],

            // ADULTS - Muay Thai
            [
                'name' => 'Muay Thai Kickboxing | Adults (Co-Ed)',
                'description' => "Monday 7:00 PM – 8:00 PM\nTuesday 7:00 PM – 8:00 PM\nWednesday 7:00 PM – 8:00 PM\nThursday 7:00 PM – 8:00 PM",
                'category' => 'Adults',
                'type' => 'Muay Thai',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Striking',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Muay Thai Kickboxing (Coach Marcus)',
                'description' => "Friday 7:00 PM – 8:00 PM",
                'category' => 'Adults',
                'type' => 'Muay Thai',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Striking',
                'instructor' => 'Coach Marcus',
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Muay Thai Fundamentals | Beginner-Friendly',
                'description' => "Saturday 1:00 PM – 2:00 PM",
                'category' => 'Adults',
                'type' => 'Muay Thai',
                'level' => 'Beginner',
                'age_group' => 'Adults',
                'format' => 'Striking',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],

            // ADULTS - BJJ
            [
                'name' => 'Brazilian Jiu-Jitsu 201 | No-Gi (Prof. Chad)',
                'description' => "Monday 7:00 PM – 8:00 PM\nTuesday 7:00 PM – 8:00 PM (No-Gi)\nWednesday 7:00 PM – 8:00 PM (Themed)",
                'category' => 'Adults',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'Intermediate',
                'age_group' => 'Adults',
                'format' => 'No-Gi',
                'instructor' => 'Prof. Chad',
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Brazilian Jiu-Jitsu 201 | Gi (Kimono)',
                'description' => "Thursday 7:00 PM – 8:00 PM",
                'category' => 'Adults',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'Intermediate',
                'age_group' => 'Adults',
                'format' => 'Gi',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Submission Grappling | No-Gi (Adults, Co-Ed)',
                'description' => "Monday 8:00 PM – 9:15 PM",
                'category' => 'Adults',
                'type' => 'Grappling',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'No-Gi',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Brazilian Jiu-Jitsu & Submission Grappling | Gi (Adults, Co-Ed)',
                'description' => "Wednesday 8:00 PM – 9:15 PM",
                'category' => 'Adults',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Gi',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Brazilian Jiu-Jitsu or Judo | Gi (Adults, Co-Ed)',
                'description' => "Thursday 8:00 PM – 9:00 PM",
                'category' => 'Adults',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Gi',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],

            // ADULTS - MMA
            [
                'name' => 'MMA Training (Gloves Required) | Striking + Grappling',
                'description' => "Tuesday 8:00 PM – 9:00 PM",
                'category' => 'Adults',
                'type' => 'MMA',
                'level' => 'Intermediate',
                'age_group' => 'Adults',
                'format' => 'Mixed',
                'instructor' => 'Prof. Chad',
                'price' => null,
                'status' => 'active',
            ],

            // WOMEN ONLY
            [
                'name' => "Women's Only Muay Thai Kickboxing",
                'description' => "Tuesday 6:00 PM – 7:00 PM\nThursday 6:00 PM – 7:00 PM",
                'category' => 'Women Only',
                'type' => 'Muay Thai',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Striking',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => "Women's Only Muay Thai | Fundamentals (Smashely)",
                'description' => "Saturday 12:00 PM – 1:00 PM",
                'category' => 'Women Only',
                'type' => 'Muay Thai',
                'level' => 'Beginner',
                'age_group' => 'Adults',
                'format' => 'Striking',
                'instructor' => 'Smashely',
                'price' => null,
                'status' => 'active',
            ],

            // FITNESS / CONDITIONING
            [
                'name' => 'Morning Warriors | Kickboxing HIT & Open Mat',
                'description' => "Monday 5:00 AM – 7:00 AM\nTuesday 5:00 AM – 7:00 AM\nWednesday 5:00 AM – 7:00 AM\nThursday 5:00 AM – 7:00 AM\nFriday 5:00 AM – 7:00 AM",
                'category' => 'Fitness / Conditioning',
                'type' => 'Kickboxing',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Fight Conditioning & Open Mat (Striking)',
                'description' => "Monday 8:00 PM – 9:00 PM\nWednesday 8:00 PM – 9:00 PM\nThursday 8:00 PM – 9:00 PM",
                'category' => 'Fitness / Conditioning',
                'type' => 'Kickboxing',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Striking',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Breathwork & Recovery | MFR + Fighter Specific Fitness',
                'description' => "Saturday 10:00 AM – 11:00 AM",
                'category' => 'Fitness / Conditioning',
                'type' => 'Fitness',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Black Belt Biomechanics | Mobility & Prehab',
                'description' => "Saturday 11:00 AM – 12:00 PM",
                'category' => 'Fitness / Conditioning',
                'type' => 'Fitness',
                'level' => 'All Levels',
                'age_group' => 'Adults',
                'format' => 'Mixed',
                'instructor' => 'Sasa',
                'price' => null,
                'status' => 'active',
            ],

            // OPEN TRAINING
            [
                'name' => 'Open Training Session | Grappling, Drilling, Sparring & Functional Fitness',
                'description' => "Friday 7:00 PM – 9:00 PM (Ages 11+)",
                'category' => 'Open Training',
                'type' => 'MMA',
                'level' => 'All Levels',
                'age_group' => 'All Ages',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Family BJJ | All-Ages Fundamentals',
                'description' => "Saturday 11:00 AM – 12:00 PM",
                'category' => 'Open Training',
                'type' => 'Brazilian Jiu-Jitsu',
                'level' => 'Beginner',
                'age_group' => 'All Ages',
                'format' => 'Grappling',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],

            // PRIVATE
            [
                'name' => 'Private Group Bookings (By Appointment)',
                'description' => "Monday 3:30 PM – 4:30 PM",
                'category' => 'Private',
                'type' => 'MMA',
                'level' => 'All Levels',
                'age_group' => 'All Ages',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Private Lessons & Groups (By Appointment)',
                'description' => "Tuesday 11:00 AM – 4:00 PM\nSaturday By Appointment",
                'category' => 'Private',
                'type' => 'MMA',
                'level' => 'All Levels',
                'age_group' => 'All Ages',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Private Lessons (SD57)',
                'description' => "Tuesday 3:00 PM – 4:00 PM",
                'category' => 'Private',
                'type' => 'MMA',
                'level' => 'All Levels',
                'age_group' => 'All Ages',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
            [
                'name' => 'Mandatory Safety & Procedure Orientation (Pre-Registered)',
                'description' => "Monday 4:30 PM – 5:00 PM\nWednesday 4:30 PM – 5:00 PM",
                'category' => 'Private',
                'type' => 'Fitness',
                'level' => 'Beginner',
                'age_group' => 'All Ages',
                'format' => 'Mixed',
                'instructor' => null,
                'price' => null,
                'status' => 'active',
            ],
        ];

        foreach ($classes as $class) {
            MartialArtsClass::create($class);
        }
    }
}
